#!/usr/bin/env python3

print("Hello person that is alive")
name = input("What is your name?\n>> ")
print("Hi " + name)


print("we took a dub yesterday") 

print("grind house") 

print("I dont like this")

print("Im rick harison and this is my pawn shop")
